export enum MovieTypes {
    GET_MOVIES_REQUEST = 'movie/GET_MOVIES_REQUEST',
    GET_MOVIES_SUCCESS = 'movie/GET_MOVIES_SUCCESS',
    GET_UPCOMING_REQUEST = 'movie/GET_UPCOMING_REQUEST',
    GET_UPCOMING_SUCCESS = 'movie/GET_UPCOMING_SUCCESS',
    GET_NOW_PLAYING_REQUEST = 'movie/GET_NOW_PLAYING_REQUEST',
    GET_NOW_PLAYING_SUCCESS = 'movie/GET_NOW_PLAYING_SUCCESS',
    GET_POPULAR_REQUEST = 'movie/GET_POPULAR_REQUEST',
    GET_POPULAR_SUCCESS = 'movie/GET_POPULAR_SUCCESS',
    GET_TOP_RATED_REQUEST = 'movie/GET_TOP_RATED_REQUEST',
    GET_TOP_RATED_SUCCESS = 'movie/GET_TOP_RATED_SUCCESS',
    GET_DISCOVER_MOVIE_REQUEST = 'movie/GET_DISCOVER_MOVIE_REQUEST',
    GET_DISCOVER_MOVIE_SUCCESS = 'movie/GET_DISCOVER_MOVIE_SUCCESS',
}
