export enum MovieTypes {
    GET_UPCOMING_REQUEST = 'movie/GET_UPCOMING_REQUEST',
    GET_UPCOMING_SUCCESS = 'movie/GET_UPCOMING_SUCCESS',
    GET_MOVIE_DETAIL_REQUEST = 'movie/GET_MOVIE_DETAIL_REQUEST',
    GET_MOVIE_DETAIL_SUCCESS = 'movie/GET_MOVIE_DETAIL_SUCCESS',
}
